# Production environment values

global:
  environment: production
postgresql:
  persistence:
    size: 50Gi
  auth:
    password: 'CHANGE-THIS-SECURE-PASSWORD'
services:
  auth:
    replicas: 3
    autoscaling:
      minReplicas: 3
      maxReplicas: 10
  video:
    replicas: 3
    autoscaling:
      minReplicas: 3
      maxReplicas: 10
  interaction:
    replicas: 3
    autoscaling:
      minReplicas: 3
      maxReplicas: 10
  notification:
    replicas: 3
    autoscaling:
      minReplicas: 3
      maxReplicas: 8
  gateway:
    replicas: 3
    autoscaling:
      minReplicas: 3
      maxReplicas: 10
  api_gateway:
    image:
      repository: ghcr.io/betuanminh22032003/tiktok_nestjs/api-gateway
      tag: v0.0.0-85725bd-202512280842
  auth_service:
    image:
      repository: ghcr.io/betuanminh22032003/tiktok_nestjs/auth-service
      tag: v0.0.0-85725bd-202512280842
  video_service:
    image:
      repository: ghcr.io/betuanminh22032003/tiktok_nestjs/video-service
      tag: v0.0.0-85725bd-202512280842
  interaction_service:
    image:
      repository: ghcr.io/betuanminh22032003/tiktok_nestjs/interaction-service
      tag: v0.0.0-85725bd-202512280842
  notification_service:
    image:
      repository: ghcr.io/betuanminh22032003/tiktok_nestjs/notification-service
      tag: v0.0.0-85725bd-202512280842
monitoring:
  enabled: true
